language: java
sudo: false
jdk:
- oraclejdk8
before_script:
- mkdir -p ext
- wget http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.11/launch4j-3.11-linux.tgz
- echo "fd1b654e5024d3f58419e05da2170d44dc5e924f1f369ebee8d2fb2e9cbd2b68  launch4j-3.11-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.11-linux.tgz
- ant fetch
install: false
script:
- mvn clean compile findbugs:check package
- ant windist
env:
  global:
    secure: hH+ndhQYLCfGaJ8XXW0GW9jO8wv4Ek0tDz3StzyVq9F+6meXOiGFIJ6MCyLPVZouxpCYj03PC0DunWAYYn+e3lgdMeOBLIg6/1BpOs5i0eHImE6O7pdo/+/jsHtR60PG9qRNfw2JXpPTI0F730o4UBi4V2eY2hWfmCIAWj61X9U=
addons:
  apt:
    packages:
    - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/cdoc
      description: idcrypt
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  file:
  - cdoc.jar
  - cdoc.exe
  provider: releases
  prerelease: true
  api-key:
    secure: "gecr55yd5+pcsZJzQRqysiPK5NtGOcwnRYXM/JGASweGBvGlrIe2iKHCnECvENK63Jyq803le5QB03XnjG2StuAmd2GH4VLKlEPR+B8AD4FpiSI6KkA52CMbDYWIttJP8apsXtKXc/E8gqhr/ldIhLtVd+shcRrwAZFuYB5UjO22K23XqqBHmVQG8PoCpi6oATIGpR9o3cwS9tM9jZm2Nr1jWz32NGzqqexzmxXqBHEHGnaZtSzYn4EKK9sYnJVmuDBvTblyuyy3/RWWfzizFp4IJD4jKDzOwTO8ckiLNPqbbbCqxx/KShkpysYGn2Xcck0NOUVNdboN+pTA9j2Sw1238YI+z5DwgaW1FT+cusWE/pJxdEBM8RV3s7On+gDkaen1CGktR+I6B7ylsTQ9dSu0kHmK8AfSHYJ+GVMOqOLB5lmMRax68DhsoQ9su52B2jK30yFS4SR1rGo2qzQ9fUu393rbZwYQNdG9QA/rXk2jxB3iWovG1N24R2o3sdVjdDyaNz78A4c8vNF9LDBUeVovm+z9/t0gp4/06BD7b+2iaVe9YYKggptTZQGH4VDv82TdzouqHeHOcPgopzu8OLBAr+KL0zIDDPzNGaOmxsNScA0RR6otDvZmHTDHc1Sp9GFJAxARocvLbqiAhC7GacDSm5SyjNk2Jym9IFGrrTw="
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - $HOME/.m2
