language: java
sudo: false
jdk:
- oraclejdk8
before_script:
  - mkdir -p ext
  - wget http://iweb.dl.sourceforge.net/project/launch4j/launch4j-3/3.8/launch4j-3.8-linux.tgz
  - echo "e0cb0240c91b3ed6ca7bb85743fd09d6d7651cc3671a5fc17f67e57b8f7a80c6  launch4j-3.8-linux.tgz" | sha256sum -c
  - tar -C ext -xzf launch4j-3.8-linux.tgz
  - ant fetch
script: ant windist
notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    secure: hH+ndhQYLCfGaJ8XXW0GW9jO8wv4Ek0tDz3StzyVq9F+6meXOiGFIJ6MCyLPVZouxpCYj03PC0DunWAYYn+e3lgdMeOBLIg6/1BpOs5i0eHImE6O7pdo/+/jsHtR60PG9qRNfw2JXpPTI0F730o4UBi4V2eY2hWfmCIAWj61X9U=

addons:
  apt:
    packages:
      - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/idcrypt
      description: idcrypt
    notification_email: martin@martinpaljak.net
    build_command_prepend: ant fetch
    build_command: ant compile
    branch_pattern: coverity

deploy:
  file:
    - idcrypt.jar
    - idcrypt.exe
  provider: releases
  api-key:
    secure: kUETLp7FylqzqjmpOdDMwVT3cPecn9gzDyipzuOV7+rL+xjL5ZxeHVNiK2QNRG1pLwih4IRhKQjPHofmUoc0pyLIfz7PjKojdpintBcHXUn7CIMhFMURd6+DmIRIX6HNVXQNd/bF8OOYV+Azfukx5FTUmB9HDbJ6L0BEHO0Dl3E=
  skip_cleanup: true
  on:
    tags: true
