language: java
sudo: false
jdk:
- oraclejdk8
before_script:
- mkdir -p ext
- wget http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.11/launch4j-3.11-linux.tgz
- echo "fd1b654e5024d3f58419e05da2170d44dc5e924f1f369ebee8d2fb2e9cbd2b68  launch4j-3.11-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.11-linux.tgz
- ant fetch
install: false
script:
- if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then exit; fi
- mvn clean compile findbugs:check package
- ant windist
env:
  global:
    secure: "H7pKwKeuySVC00HCvSAYbLzNkviq+Pn2qM/+5gSxixYaQCpMYR3+91svnev28ILGUeuhf7Pa067msMuAb7SB1ZkIRJSTKuLqAvCcCRPQ96ScsrAI+V/O0AyPTi9suHLA7DQz1Zk3PmFQuxKYRT5G/EpWIxhsZD3Rd8adsQ4l7l5ab93jf68mrRHm5jgoEJYJvFphFiIoiwVWH/c7rJYnHYwo6QJpHsUcxYwqFYW5Gc2/+ePQHSRWG2cLXzh03CyJlwrgKOXuemhzhtkob4iibz+1S2bL23VouyyEyW5g/J34OUQvSenalNccscW1WmkrDkon4EiLsPZr+6CuEHkm4YC07VJ6HKakxu51xNGDqWixuUniJ+oRTUaJ33RYL/+Zsa4RsY+Fy2JaNptfpAZxtv3eCSrCeeMaBMMj2zgaE8QhOD7wW4BU2tFMlCR9mgU+8Hf3TaDayjKc5qQ5bbTDw7KbPcK3RFZYOA+so1eVcaMeiMZ4WDjfPRCOvlEooN94UxL2sTu2CDGRWbT8XDwVjAVAOB+xq3kYTGZLup8hDC8ACI6TDDetws3reg6RnOJBvpeHb0t6+i1rwQm6VaNf8CuNb4NmqyAiCowmB9MDdbMnRFJtZSvO2kOVAc8lNxjNglsnYQ+lBClr0t+X/FIQD527NQLKlKSXZ3aN18SSH9w="
addons:
  apt:
    packages:
    - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/cdoc
      description: idcrypt
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  file:
  - cdoc.jar
  - cdoc.exe
  provider: releases
  prerelease: true
  api-key:
    secure: "gecr55yd5+pcsZJzQRqysiPK5NtGOcwnRYXM/JGASweGBvGlrIe2iKHCnECvENK63Jyq803le5QB03XnjG2StuAmd2GH4VLKlEPR+B8AD4FpiSI6KkA52CMbDYWIttJP8apsXtKXc/E8gqhr/ldIhLtVd+shcRrwAZFuYB5UjO22K23XqqBHmVQG8PoCpi6oATIGpR9o3cwS9tM9jZm2Nr1jWz32NGzqqexzmxXqBHEHGnaZtSzYn4EKK9sYnJVmuDBvTblyuyy3/RWWfzizFp4IJD4jKDzOwTO8ckiLNPqbbbCqxx/KShkpysYGn2Xcck0NOUVNdboN+pTA9j2Sw1238YI+z5DwgaW1FT+cusWE/pJxdEBM8RV3s7On+gDkaen1CGktR+I6B7ylsTQ9dSu0kHmK8AfSHYJ+GVMOqOLB5lmMRax68DhsoQ9su52B2jK30yFS4SR1rGo2qzQ9fUu393rbZwYQNdG9QA/rXk2jxB3iWovG1N24R2o3sdVjdDyaNz78A4c8vNF9LDBUeVovm+z9/t0gp4/06BD7b+2iaVe9YYKggptTZQGH4VDv82TdzouqHeHOcPgopzu8OLBAr+KL0zIDDPzNGaOmxsNScA0RR6otDvZmHTDHc1Sp9GFJAxARocvLbqiAhC7GacDSm5SyjNk2Jym9IFGrrTw="
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - $HOME/.m2
